name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Setup Python
        uses: actions/setup-python@v5  # Atualizado para v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          [ -f requirements.txt ] && pip install -r requirements.txt

      - name: Build .app bundle
        run: |
          pyinstaller CalmDesk_mac.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: CalmDesk-macOS
          path: dist/CalmDesk.app